disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
- force_cast
- force_try
- identifier_name
- implicit_getter
- generic_type_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- .build
